### ISSUE TITLE
Is it universally compatible with all syntaxes?

### ISSUE THREAD

**Issue by pykong** [jk4837/ShowDefinitionEx#1]
@jk4837 Hi. Thanks for putting up this Sublime Text plugin.
I guess I happened to be the first to install it.

I wonder whether I could use it with other syntaxes (say Python) as mere C, since the default settings imply this. If so could you add a sentence or two to the readme to make it clearer to users to what extent they may use this package?

**Comment by jk4837** [comment]
Hi pykong, thanks for using.
In theory, It could be use with every syntaxes that has the correct syntax template.
I will add a sentence to the readme to explain this.
I usually use with C, C++, and have some test with Python, Javascript, Makefile before upload.
Do you have any issue using with Python or other syntax?

**Comment by pykong** [comment]
@jk4837 
Thanks for your response.

No I haven't had any issues using Python or JavaScript, as I am still in the process of figuring out the exact settings to put in.

I am looking forward to the updated readme.

**Comment by jk4837** [comment]
I had simply added a sentence to readme.
Once the plugin is more complete, I will add content about other options.
