### ISSUE TITLE
Missing menu settings

### ISSUE THREAD

**Issue by kallookoo** [jk4837/ShowDefinitionEx#2]
Hi,
Thanks for this package, but not exists the typical menu for the settings.
It would be possible to add it?

**Comment by jk4837** [comment]
Yes, just need some time to figure it out.

**Comment by kallookoo** [comment]
Hi, @jk4837 

Here's how I do I https://github.com/kallookoo/WebSearch/blob/master/Main.sublime-menu and you have more info in http://docs.sublimetext.info/en/latest/reference/menus.html

**Comment by jk4837** [comment]
Thanks for the information.
I just follow other plugin to build a menu.
You can see it after upgrade to ver 1.0.4.

Instead of using command "open_file", I use "[edit_settings](http://docs.sublimetext.info/en/latest/reference/commands.html?highlight=edit_settings)" to open the setting files.
I think it's more convinient for user to edit.

**Comment by kallookoo** [comment]
The edit_settings option, it is only available for the sublime text 3 >= 3124.
Therefore, open_file is used if you want to give more compatibility.

**Comment by jk4837** [comment]
Oops, I didn't see it.
I'll adjust this on next version.
Thanks!

**Comment by pykong** [comment]
[PackageDev](https://packagecontrol.io/packages/PackageDev) can create menus for you easily, amongst many other useful things. I use it to bootstrap any new plugin I am creating.

This might also be relevant: [subliime_lib](https://github.com/SublimeText/sublime_lib)

**Comment by jk4837** [comment]
@pykong 
Thanks for so many useful tool, I'll take a look on it.

@kallookoo 
I discover that this package are not support old version, so I'll adjust the setting on Package Control to make this package only compatible with ST3 (ver >= 3124).
