### ISSUE TITLE
Php

### ISSUE THREAD

**Issue by mercurykd** [jk4837/ShowDefinitionEx#3]
Hi, thanks for plugin!
How use in php syntax?
Plugin show docblock description?

**Comment by jk4837** [comment]
Hi,
I haven't try plugin in php syntax, but it should work fine, just press `F10` to enable this plugin.

This plugin does not show dockblock description, I tried to add, but I think it's too much information for the popup
![image](https://user-images.githubusercontent.com/10583408/51368341-f9332b00-1b29-11e9-9e13-247a4f72663c.png)

**Comment by mercurykd** [comment]
Works, but not on all functions. Need some kind of log? How can I do it?

**Comment by mercurykd** [comment]
I apologize. The function definition display is running. Only in the embedded solution shows where the function is called, and you do not?

**Comment by jk4837** [comment]
Yes, my plugin only show definitions, not references.
