### ISSUE TITLE
this plugins could not get the class definition

### ISSUE THREAD

**Issue by EricaEden** [jk4837/ShowDefinitionEx#4]
I think it can get more imporvement by show more definition, like class , module...

**Comment by jk4837** [comment]
It should show definition now.
What's your syntax?

**Comment by EricaEden** [comment]
yes, I found it when I check the code. 
but I think there is something issue in ShowDefinitionExCommand.show
1.
Because the view which you on_hover may not equal sublime.active_window().active_view()
2.
if I open some extra file not in my project, there is not hint.

**Comment by jk4837** [comment]
1. It's a bug.
If active_view and on_hover view are not the same syntax, it will causing using wrong syntax to parse the file, and get the wrong information. 
I will fix it today.
2. This plugin base on built-in indexing result, it only index the file which is in the workspace, you can turn off this plugin and using the built-in show_definition, if it shows the file you want, but my plugin did not, then that may be a bug.

Thanks for your comment!

**Comment by jk4837** [comment]
@EricaEden 
I had released a new version 1.0.9 for the bug.
If you don't have any questions, I will end this issue.
